### ISSUE TITLE
Library is unusable with version locked dependencies

### ISSUE THREAD

**Issue by ShayBox** [gorilla-devs/furse#4]
I can't use this library if every dependency is version locked, it would require also version locking every shared dependency to the exact same version...  
Version lock to minor versions using `x.x.x` instead of `~x.x.x`  

EDIT:  
For example, if `url` had been declared as  
`url = { version = "2.2.2", features = ["serde"] }`  
I could have used `url = "2.3.1"` without issue, as newer minor updates are semver compatible.  
See here https://github.com/rust-lang/cargo/issues/6584

Similarly this change should be made for [ferinth](https://github.com/gorilla-devs/ferinth) and [libium](https://github.com/gorilla-devs/libium) as they're libraries, but this practice is acceptable for projects such as [ferium](https://github.com/gorilla-devs/ferium) as it's an application not a library.

**Comment by theRookieCoder** [comment]
I haven't fully locked dependency versions, I currently have them locked to the minor versions because they can introduce breaking changes that make the code not compile. I'll have to see what I can do about this though.

**Comment by ShayBox** [comment]
As far as I can tell the version numbers are currently locked to the patch versions, the default without a prefix being to minor versions, while only major updates should contain breaking changes, minor updates should not.  
Though this is not always the case, generally version numbers follow [semver](https://semver.org)  
The order being Major.Minor.Patch (ex. 1.0.2)

**Comment by theRookieCoder** [comment]
> only major updates should contain breaking changes, minor updates should not.

Well I did experience such changes that completely broke my builds. This had happened multiple times so I locked my minor versions and haven't had the problem since. I'll try reverting this change and see what happens.
